# Generated by Django 4.1.3 on 2022-12-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_productingredient_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="productingredient",
            name="Qty",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productingredient",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
