# Generated by Django 4.1.3 on 2022-12-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0002_productingredient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bulk", models.IntegerField()),
                ("bulk_quantity", models.IntegerField(default=1)),
                (
                    "unit_type",
                    models.IntegerField(
                        choices=[
                            (1, "KG"),
                            (2, "G"),
                            (3, "MG"),
                            (4, "L"),
                            (5, "ML"),
                            (6, "Pieces"),
                        ]
                    ),
                ),
                (
                    "stock_type",
                    models.IntegerField(choices=[(1, "Stock-In"), (2, "Stock-Out")]),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
