# Generated by Django 4.1.3 on 2022-12-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="stock",
            table="stocks",
        ),
    ]
