# Generated by Django 4.1.3 on 2022-12-09 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("raw_material", "0003_alter_productrawmaterial_table"),
        ("stock", "0002_alter_stock_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="product",
        ),
        migrations.AddField(
            model_name="stock",
            name="raw_material",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="raw_material.productrawmaterial",
            ),
            preserve_default=False,
        ),
    ]
