# Generated by Django 4.1.3 on 2023-01-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_remove_stock_product_stock_raw_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
