# Generated by Django 4.1.3 on 2023-01-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_stock_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="bulk_quantity",
        ),
    ]
