# Generated by Django 4.1.3 on 2023-01-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_remove_stock_bulk_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="bulk",
            field=models.FloatField(),
        ),
    ]
