# Generated by Django 4.1.3 on 2022-12-02 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_alter_users_is_active_alter_users_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRawMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("bulk", models.IntegerField()),
                ("bulk_quantity", models.IntegerField(default=1)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "KG"),
                            (2, "G"),
                            (3, "MG"),
                            (4, "L"),
                            (5, "ML"),
                            (6, "Pieces"),
                        ]
                    ),
                ),
                ("min_stock", models.FloatField()),
                ("total_stock", models.FloatField()),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.shop"
                    ),
                ),
            ],
        ),
    ]
