# Generated by Django 4.1.3 on 2022-12-09 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("raw_material", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productrawmaterial",
            name="bulk",
        ),
        migrations.RemoveField(
            model_name="productrawmaterial",
            name="bulk_quantity",
        ),
        migrations.RemoveField(
            model_name="productrawmaterial",
            name="total_stock",
        ),
        migrations.RemoveField(
            model_name="productrawmaterial",
            name="type",
        ),
    ]
