# Generated by Django 4.1.3 on 2022-12-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("raw_material", "0002_remove_productrawmaterial_bulk_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="productrawmaterial",
            table="raw_materials",
        ),
    ]
