# Generated by Django 4.1.3 on 2022-12-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
