# Generated by Django 4.1.3 on 2022-12-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_users_is_active_alter_users_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="users",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="name"),
        ),
    ]
