# Generated by Django 4.1.3 on 2022-12-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_users_phone"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="shop",
            table="shop",
        ),
    ]
