# Generated by Django 4.1.3 on 2023-01-04 05:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_shop_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=15, region=None, unique=True
            ),
        ),
    ]
